{% set name = "overrides" %}
{% set version = "2.3" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "8e2657ade554b662e450105b79cf5fffdc48bcf687af1f016498e275ca8fab55" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - pip
    - python
  run:
    - python

test:
  imports:
    - overrides

about:
  home: https://github.com/mkorpela/overrides
  license: Apache-2.0
  license_family: APACHE
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: A decorator to automatically detect mismatch when overriding a method.
  description: A decorator to automatically detect mismatch when overriding a method.
  doc_url: https://github.com/mkorpela/overrides
  dev_url: https://github.com/mkorpela/overrides

extra:
  recipe-maintainers:
    - nelson-liu
