travis:
  secure:
    BINSTAR_TOKEN: Ttgn1ZXSaIFP86EYJPE0sLHXfLAVBG331jtXRDcbKm9YIEFJ8gG4WcZ8FvRILsH0GrsAPRuEWrOWv+DYNiXD8Pj9bXtqvSbfhomW20qsBocGdQfam0ax4CngR2Rqd+BSG8FJTZaDJc6Ywk+smY7xwUqxl3TbJJ/5p1/JrQ1Y2OXMmKLE25uXv65EpUbAH3S+ilddVeh9YaS8proQF4TYpNQ8XaL54cq82f9PGLaoUpinH/jrvcMKI+6uwPfp283T1eRnJzHpOm/X9Lg+276CNpcqi5Y0IcgTF9q3b7hYv9PMh+hwvZW8QtrzY5uCGsg8UBENpNA5mCZ0SllvvtEkwFAqZECsD2jkJzZyKvWyvCWw84KAqTbH0H0BzxYx/QAHui2NVM7m1my96ghNadOW/JV1wC9fVcDTkuZIK2RPgcqA/a/klIKFUt8XRaLwBAmtBjaXqPRxd6APZ/w3HCF6uQdcV6gwh39KA6xhN1j4eBWLImY+TojclaJMZx42MJQVw37QukIwGe9FbqxVmAm3ZH0XSV99fZ0ikSZtSCYHbppCq5w//WluJZTuFiwINp15o+S676nulJ6zUFk/YFK0HZI5uKxMaQdVCA5Q4xNZbmgJ/YCsiy/ylaQOUNp6azgJ1v8okMX+G5l6KewmK34fR+TuHxDzMke47vXoZXWGtfY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
