travis:
  secure:
    BINSTAR_TOKEN: XO9RG/OOMeJ9IfFsyktPsAaEbTS7d/lJOhx8elBDcshtIQvRqdeash3EyYJOAJw3ifN+3j+zAF2X5/i6CbuEusfDuqwxgHivgSC8hNxW+5coqlCPNBBR+8ZZSTs9zBIBTHNaKcfNJWhCXM7JHkuJdR9AEDGYzlC2vgzSaLgWuBuedaM9TFy+o4y50/t1fj2Bh9E7zaGGGzEMoQ14gVjAi73G9rjJgL2U2JyE/99whkF7sFgkBwXOT2iEpmwLwAgIFQIKPCjp7W8hYJZx5QWIM9tcJkIFzC19KtHDsEzU5Sqq0SdDuPpEk7sbP6kVZa3uNJ5pAGW2OGezSX3bDnY+xFeMYXfiRsRKbxoBWnJiOaVZTjJz9xP9+RsErICkEOI5/DWN5LoRDxAv+jc1rao+1sK6lbBfcWOnz5No0Nux8AGE76KSiT1A+kcE88QS62GmI/WzGbWMPOXmJrqN2/o2jiS4F91gbDJ+NJ6un0OCzvTpeDpBwjPeBeHmc4PO+ws0bFmP+tIQCzyKKuQzLgBwGQgB2HvI9qEXeFjJ66YLFrJ5ZcOEp8rFBROYsBxd+ywawNQ4scrgs1boVSOfjbNrorisYMAeqIXwj3nbO1Vlr9797Rs+K+6obi97Q0/BekuXXn/ali3RELRvIEmgji5ScmARQzGep/bh8639Ds+7eVU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
